# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true - removed due to gh-pages build errors

# Setup
title:               full stop.
tagline:             'a secret blog'
description:         'based on the Naringu theme for Jekyll'
url:                 https://kellyfesler.com
baseurl:             /
paginate:            7

# About/contact
author:
  name:              K
  url:               https://kellyfesler.com

# Custom vars
version:             1.0

# Social Media
github:				http://github.com/praepunctis

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
