# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               full stop.
tagline:             'a secret blog'
description:         'based on the Naringu theme for Jekyll'
url:                 https://kellyfesler.com
baseurl:             /full-stop
paginate:            7

# About/contact
author:
  name:              K
  url:               https://kellyfesler.com

# Custom vars
version:             1.0

# Social Media
github:				http://github.com/praepunctis

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
